### ISSUE TITLE
Update the styleguide to use spress

### ISSUE THREAD

**Issue by zendoodles** [MidCamp/Hatter#2]
Sculpin isn't a thing anymore... 

@see https://github.com/MidCamp/midcamp/blob/develop/composer.json#L68
@see https://github.com/MidCamp/midcamp/tree/develop/styleguide

We also need to update the README on this repo.

**Comment by zendoodles** [comment]
@aCyborg Is there anything missing here?

**Comment by labbydev** [comment]
Closing this issue since it appears it is done.
